remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
repository: "academicpages/academicpages.github.io"

title: Bowen Li
logo: /assets/img/bowen.jpg
description: PhD Student<br />Academy of Mathematics and Systems Science<br />Chinese Academy of Sciences
contact: Institute of Computational Mathematics and Scientific/Engineering Computing,<br />Academy of Mathematics and Systems Science,<br />No.55, ZhongGuanCun East Road, Beijing, China, 100190

nav:
- name: Home
  link: /
- name: Research
  link: /pages/research.html
