remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Minimal theme
description: PhD Student<br />Academy of Mathematics and Systems Science<br />Chinese Academy of Sciences
